name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    
    - name: Pull DVC data
      run: dvc pull
    
    - name: Train model
      run: python src/train.py
    
    - name: Build BentoML bundle
      run: bentoml build
    
    - name: Run tests (se houver)
      run: |
        # Adicione seus testes aqui
        # pytest tests/
    
    - name: Deploy (simulado)
      run: |
        echo "Simulando deploy do modelo..."
        # Adicione seus comandos de deploy aqui